name: filiera_token_front_end
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  bcrypt: ^1.1.3
  desktop_window: ^0.4.0
  dio: ^5.4.1
  eva_icons_flutter: ^3.1.0
  flutter:
    sdk: flutter
  flutter_pw_validator: ^1.6.0
  flutter_router: ^1.2.0
  flutter_secure_storage: ^9.0.0
  flutter_social_button: ^1.1.4+1
  flutter_spinkit: ^5.2.0
  get: ^4.6.6
  get_it: ^7.6.7
  go_router: ^13.2.0
  http: ^1.2.1
  image_picker: ^1.0.7
  json_serializable: ^6.7.1
  provider: ^6.1.1


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

  

flutter:
  uses-material-design: true
